/**
 * Role: 맛집 목 데이터 및 카테고리/무드 설정
 * Key Features: 레스토랑 배열, 카테고리 맵, 무드 맵
 */

/* 음식 카테고리 — 이미지·아이콘·테마 색상 매핑 */
const CATEGORIES = {
  한식:   { color: '#FF142D', image: 'img/food/img002.png', icon: 'img/icon/img002.png' },
  양식:   { color: '#3D7EFF', image: 'img/food/img003.png', icon: 'img/icon/img003.png' },
  일식:   { color: '#FFD600', image: 'img/food/img004.png', icon: 'img/icon/img004.png' },
  분식:   { color: '#FF7A2B', image: 'img/food/img005.png', icon: 'img/icon/img005.png' },
  디저트: { color: '#B870FF', image: 'img/food/img006.png', icon: 'img/icon/img006.png' },
};

/* 무드/취향 키워드 — 테마 색상 매핑 */
const MOODS = {
  매콤:     { color: '#FF142D' },
  느끼:     { color: '#FF7A2B' },
  가성비:   { color: '#00C77F' },
  플렉스:   { color: '#FFD600' },
  혼밥:     { color: '#3D7EFF' },
  로컬맛집: { color: '#B870FF' },
};

/* 레스토랑 목 데이터 — 12개 이상 */
const RESTAURANTS = [
  {
    id: 1,
    name: '을지로 골뱅이',
    category: '한식',
    tags: ['한식', '매콤', '로컬맛집'],
    rating: 4.8, reviewCount: 342,
    distance: 0.8, walkTime: 12,
    address: '서울 중구 을지로3가 354-1',
    thumbnail: 'img/food/img002.png',
    description: '40년 전통의 을지로 골뱅이 전문점. 매콤한 양념과 쫄깃한 면 궁합이 일품.',
    priceRange: '1만원대',
  },
  {
    id: 2,
    name: '스시 나카무라',
    category: '일식',
    tags: ['일식', '플렉스', '혼밥'],
    rating: 4.9, reviewCount: 128,
    distance: 1.4, walkTime: 20,
    address: '서울 강남구 청담동 82-4',
    thumbnail: 'img/food/img004.png',
    description: '오마카세 스타일의 정통 일식 스시 바. 최상급 재료만 엄선해 사용.',
    priceRange: '10만원대',
  },
  {
    id: 3,
    name: '파스타 소스토',
    category: '양식',
    tags: ['양식', '느끼', '플렉스'],
    rating: 4.7, reviewCount: 256,
    distance: 0.5, walkTime: 8,
    address: '서울 마포구 연남동 391-5',
    thumbnail: 'img/food/img003.png',
    description: '이탈리아 직수입 재료로 만드는 정통 파스타와 나폴리 화덕 피자.',
    priceRange: '3만원대',
  },
  {
    id: 4,
    name: '순대국밥 박가네',
    category: '한식',
    tags: ['한식', '매콤', '가성비', '로컬맛집'],
    rating: 4.6, reviewCount: 511,
    distance: 0.3, walkTime: 5,
    address: '서울 중구 황학동 88',
    thumbnail: 'img/food/img002.png',
    description: '진한 사골 육수에 두툼한 순대. 동네 주민들이 30년째 인정하는 가성비 맛집.',
    priceRange: '8천원대',
  },
  {
    id: 5,
    name: '떡볶이 왕가',
    category: '분식',
    tags: ['분식', '매콤', '가성비'],
    rating: 4.5, reviewCount: 890,
    distance: 0.2, walkTime: 3,
    address: '서울 서대문구 신촌동 63-1',
    thumbnail: 'img/food/img005.png',
    description: '쫄깃한 쌀떡에 매콤달콤한 양념. 신촌 터줏대감 30년 전통.',
    priceRange: '5천원대',
  },
  {
    id: 6,
    name: '카페 드 마르',
    category: '디저트',
    tags: ['디저트', '느끼', '플렉스', '혼밥'],
    rating: 4.8, reviewCount: 203,
    distance: 1.0, walkTime: 15,
    address: '서울 종로구 익선동 40-1',
    thumbnail: 'img/food/img006.png',
    description: '프랑스 파티시에가 직접 만드는 수제 케이크와 마카롱. 아늑한 단독 건물.',
    priceRange: '2만원대',
  },
  {
    id: 7,
    name: '라멘 히로',
    category: '일식',
    tags: ['일식', '느끼', '혼밥', '로컬맛집'],
    rating: 4.7, reviewCount: 445,
    distance: 0.7, walkTime: 10,
    address: '서울 용산구 이태원동 218-6',
    thumbnail: 'img/food/img004.png',
    description: '18시간 우려낸 진한 돈코츠 육수. 면의 쫄깃함과 차슈가 조화롭다.',
    priceRange: '1만 5천원대',
  },
  {
    id: 8,
    name: '버거 프레스',
    category: '양식',
    tags: ['양식', '느끼', '가성비'],
    rating: 4.4, reviewCount: 667,
    distance: 0.5, walkTime: 7,
    address: '서울 마포구 홍대 402-3',
    thumbnail: 'img/food/img003.png',
    description: '매일 직접 패티를 갈아 만드는 수제 버거 전문점. 두툼한 패티가 자랑.',
    priceRange: '1만 2천원대',
  },
  {
    id: 9,
    name: '냉면 평양옥',
    category: '한식',
    tags: ['한식', '로컬맛집', '가성비'],
    rating: 4.9, reviewCount: 289,
    distance: 1.0, walkTime: 14,
    address: '서울 중구 을지로 221',
    thumbnail: 'img/food/img002.png',
    description: '순수 메밀로 만드는 전통 평양냉면. 심플하지만 깊고 진한 사골 육수.',
    priceRange: '1만 2천원대',
  },
  {
    id: 10,
    name: '단팥빵 토키',
    category: '디저트',
    tags: ['디저트', '가성비', '혼밥'],
    rating: 4.6, reviewCount: 178,
    distance: 1.2, walkTime: 18,
    address: '서울 성동구 성수동 291-25',
    thumbnail: 'img/food/img006.png',
    description: '매일 아침 굽는 신선한 수제 단팥빵. 국내산 통팥과 건강한 재료만 사용.',
    priceRange: '3천원대',
  },
  {
    id: 11,
    name: '김밥 명인',
    category: '분식',
    tags: ['분식', '가성비', '혼밥'],
    rating: 4.3, reviewCount: 1024,
    distance: 0.3, walkTime: 4,
    address: '서울 광진구 건대입구 15-8',
    thumbnail: 'img/food/img005.png',
    description: '11가지 특제 김밥과 라볶이를 합리적인 가격에. 언제나 긴 줄이 증명.',
    priceRange: '5천원대',
  },
  {
    id: 12,
    name: '이자카야 사쿠라',
    category: '일식',
    tags: ['일식', '느끼', '플렉스', '로컬맛집'],
    rating: 4.7, reviewCount: 312,
    distance: 1.8, walkTime: 25,
    address: '서울 강남구 압구정 119-2',
    thumbnail: 'img/food/img004.png',
    description: '오사카 스타일 이자카야. 엄선한 사케와 창작 안주의 완벽한 조합.',
    priceRange: '4만원대',
  },
  {
    id: 13,
    name: '마라탕 홍',
    category: '한식',
    tags: ['한식', '매콤', '혼밥'],
    rating: 4.5, reviewCount: 732,
    distance: 0.6, walkTime: 9,
    address: '서울 강남구 역삼동 814-6',
    thumbnail: 'img/food/img002.png',
    description: '얼얼한 마라 향신료의 깊은 맛. 재료를 직접 고르는 자유로운 한 끼.',
    priceRange: '1만 8천원대',
  },
  {
    id: 14,
    name: '피자 마르게리타',
    category: '양식',
    tags: ['양식', '느끼', '로컬맛집'],
    rating: 4.6, reviewCount: 421,
    distance: 0.9, walkTime: 13,
    address: '서울 송파구 잠실동 212-5',
    thumbnail: 'img/food/img003.png',
    description: '나폴리 정통 방식으로 구워내는 화덕 피자. 얇고 바삭한 크러스트가 특징.',
    priceRange: '2만 5천원대',
  },
];
